ALTER TABLE athletes DISABLE ROW LEVEL SECURITY;
ALTER TABLE athlete_gap_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE athlete_readiness_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE athlete_school_interest_results DISABLE ROW LEVEL SECURITY;ALTER TABLE athlete_weekly_plans DISABLE ROW LEVEL SECURITY;